version: 2
formats: all
build:
  os: ubuntu-22.04 # Or ubuntu-20.04
  tools:
    python: "3.9" # Adjust based on your project
python:
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements: ["docs"]
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py
